crm_customer:
    resource: "@CRMCustomerBundle/Resources/config/routing.yml"
    prefix:   /customer

crm_core:
    resource: "@CRMCoreBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#REST 
rest : 
  type : rest 
  resource : "routing_rest.yml"
  prefix : /api

