crm_account:
    resource: "@CRMAccountBundle/Resources/config/routing.yml"
    prefix:   /

crm_core:
    resource: "@CRMCoreBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

