<?php

namespace CRM\CustomerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends EntityRepository
{
    public function findNewAccounts($beforeDay)
    {
        $qb = $this->createQueryBuilder('a')
                   ->where('a.CreationTime >= :beforeDay')
                    ->setParameter('beforeDay', date_modify(new \DateTime(),'-'.$beforeDay.' day'));
                                    
        return $qb->getQuery()
                  ->getArrayResult();
    }
    
    /*
    public function getAllAccounts()
    {
        $qb = $this->createQueryBuilder('a');
        return $qb->getQuery()
                  ->getArrayResult();
    }
     */
}
