crm_account_home:
    path:     /
    defaults: { _controller: CRMAccountBundle:Account:index }
    
crm_account_add:
    path:     /add
    defaults: { _controller: CRMAccountBundle:Account:add }

crm_account_list_json:
    path:     /listAccounts
    defaults: { _controller: CRMAccountBundle:Account:listAccountsJson }     
    
crm_account_view:
    path:     /{slug}
    defaults: { _controller: CRMAccountBundle:Account:view }  

 