crm_account_homepage:
    path:     /
    defaults: { _controller: CRMAccountBundle:Account:index }
    
crm_account_add:
    path:     /add
    defaults: { _controller: CRMAccountBundle:Account:add }  

